//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copasa.Sigos.Console.SRServidorFTP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SRServidorFTP.FilesSoap")]
    public interface FilesSoap {
        
        // CODEGEN: Generating message contract since element name nomeArquivo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletaArquivo", ReplyAction="*")]
        Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoResponse DeletaArquivo(Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletaArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoResponse> DeletaArquivoAsync(Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequest request);
        
        // CODEGEN: Generating message contract since element name nomeArquivo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecebeBytesArquivo", ReplyAction="*")]
        Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoResponse RecebeBytesArquivo(Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecebeBytesArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoResponse> RecebeBytesArquivoAsync(Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequest request);
        
        // CODEGEN: Generating message contract since element name nomeArquivo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaArquivo", ReplyAction="*")]
        Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoResponse EnviaArquivo(Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoResponse> EnviaArquivoAsync(Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletaArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletaArquivo", Namespace="http://tempuri.org/", Order=0)]
        public Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequestBody Body;
        
        public DeletaArquivoRequest() {
        }
        
        public DeletaArquivoRequest(Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletaArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nomeArquivo;
        
        public DeletaArquivoRequestBody() {
        }
        
        public DeletaArquivoRequestBody(string nomeArquivo) {
            this.nomeArquivo = nomeArquivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeletaArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeletaArquivoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoResponseBody Body;
        
        public DeletaArquivoResponse() {
        }
        
        public DeletaArquivoResponse(Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeletaArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeletaArquivoResult;
        
        public DeletaArquivoResponseBody() {
        }
        
        public DeletaArquivoResponseBody(bool DeletaArquivoResult) {
            this.DeletaArquivoResult = DeletaArquivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecebeBytesArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecebeBytesArquivo", Namespace="http://tempuri.org/", Order=0)]
        public Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequestBody Body;
        
        public RecebeBytesArquivoRequest() {
        }
        
        public RecebeBytesArquivoRequest(Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecebeBytesArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nomeArquivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] dadosUpload;
        
        public RecebeBytesArquivoRequestBody() {
        }
        
        public RecebeBytesArquivoRequestBody(string nomeArquivo, byte[] dadosUpload) {
            this.nomeArquivo = nomeArquivo;
            this.dadosUpload = dadosUpload;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RecebeBytesArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RecebeBytesArquivoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoResponseBody Body;
        
        public RecebeBytesArquivoResponse() {
        }
        
        public RecebeBytesArquivoResponse(Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RecebeBytesArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RecebeBytesArquivoResult;
        
        public RecebeBytesArquivoResponseBody() {
        }
        
        public RecebeBytesArquivoResponseBody(string RecebeBytesArquivoResult) {
            this.RecebeBytesArquivoResult = RecebeBytesArquivoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaArquivo", Namespace="http://tempuri.org/", Order=0)]
        public Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequestBody Body;
        
        public EnviaArquivoRequest() {
        }
        
        public EnviaArquivoRequest(Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nomeArquivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string identificadorlote;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string urlFtp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string usuarioFtp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string senhaFtp;
        
        public EnviaArquivoRequestBody() {
        }
        
        public EnviaArquivoRequestBody(string nomeArquivo, string identificadorlote, string urlFtp, string usuarioFtp, string senhaFtp) {
            this.nomeArquivo = nomeArquivo;
            this.identificadorlote = identificadorlote;
            this.urlFtp = urlFtp;
            this.usuarioFtp = usuarioFtp;
            this.senhaFtp = senhaFtp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaArquivoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoResponseBody Body;
        
        public EnviaArquivoResponse() {
        }
        
        public EnviaArquivoResponse(Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviaArquivoResult;
        
        public EnviaArquivoResponseBody() {
        }
        
        public EnviaArquivoResponseBody(string EnviaArquivoResult) {
            this.EnviaArquivoResult = EnviaArquivoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FilesSoapChannel : Copasa.Sigos.Console.SRServidorFTP.FilesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FilesSoapClient : System.ServiceModel.ClientBase<Copasa.Sigos.Console.SRServidorFTP.FilesSoap>, Copasa.Sigos.Console.SRServidorFTP.FilesSoap {
        
        public FilesSoapClient() {
        }
        
        public FilesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FilesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FilesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoResponse Copasa.Sigos.Console.SRServidorFTP.FilesSoap.DeletaArquivo(Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequest request) {
            return base.Channel.DeletaArquivo(request);
        }
        
        public bool DeletaArquivo(string nomeArquivo) {
            Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequest inValue = new Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequest();
            inValue.Body = new Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequestBody();
            inValue.Body.nomeArquivo = nomeArquivo;
            Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoResponse retVal = ((Copasa.Sigos.Console.SRServidorFTP.FilesSoap)(this)).DeletaArquivo(inValue);
            return retVal.Body.DeletaArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoResponse> Copasa.Sigos.Console.SRServidorFTP.FilesSoap.DeletaArquivoAsync(Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequest request) {
            return base.Channel.DeletaArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoResponse> DeletaArquivoAsync(string nomeArquivo) {
            Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequest inValue = new Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequest();
            inValue.Body = new Copasa.Sigos.Console.SRServidorFTP.DeletaArquivoRequestBody();
            inValue.Body.nomeArquivo = nomeArquivo;
            return ((Copasa.Sigos.Console.SRServidorFTP.FilesSoap)(this)).DeletaArquivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoResponse Copasa.Sigos.Console.SRServidorFTP.FilesSoap.RecebeBytesArquivo(Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequest request) {
            return base.Channel.RecebeBytesArquivo(request);
        }
        
        public string RecebeBytesArquivo(string nomeArquivo, byte[] dadosUpload) {
            Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequest inValue = new Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequest();
            inValue.Body = new Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequestBody();
            inValue.Body.nomeArquivo = nomeArquivo;
            inValue.Body.dadosUpload = dadosUpload;
            Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoResponse retVal = ((Copasa.Sigos.Console.SRServidorFTP.FilesSoap)(this)).RecebeBytesArquivo(inValue);
            return retVal.Body.RecebeBytesArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoResponse> Copasa.Sigos.Console.SRServidorFTP.FilesSoap.RecebeBytesArquivoAsync(Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequest request) {
            return base.Channel.RecebeBytesArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoResponse> RecebeBytesArquivoAsync(string nomeArquivo, byte[] dadosUpload) {
            Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequest inValue = new Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequest();
            inValue.Body = new Copasa.Sigos.Console.SRServidorFTP.RecebeBytesArquivoRequestBody();
            inValue.Body.nomeArquivo = nomeArquivo;
            inValue.Body.dadosUpload = dadosUpload;
            return ((Copasa.Sigos.Console.SRServidorFTP.FilesSoap)(this)).RecebeBytesArquivoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoResponse Copasa.Sigos.Console.SRServidorFTP.FilesSoap.EnviaArquivo(Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequest request) {
            return base.Channel.EnviaArquivo(request);
        }
        
        public string EnviaArquivo(string nomeArquivo, string identificadorlote, string urlFtp, string usuarioFtp, string senhaFtp) {
            Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequest inValue = new Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequest();
            inValue.Body = new Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequestBody();
            inValue.Body.nomeArquivo = nomeArquivo;
            inValue.Body.identificadorlote = identificadorlote;
            inValue.Body.urlFtp = urlFtp;
            inValue.Body.usuarioFtp = usuarioFtp;
            inValue.Body.senhaFtp = senhaFtp;
            Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoResponse retVal = ((Copasa.Sigos.Console.SRServidorFTP.FilesSoap)(this)).EnviaArquivo(inValue);
            return retVal.Body.EnviaArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoResponse> Copasa.Sigos.Console.SRServidorFTP.FilesSoap.EnviaArquivoAsync(Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequest request) {
            return base.Channel.EnviaArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoResponse> EnviaArquivoAsync(string nomeArquivo, string identificadorlote, string urlFtp, string usuarioFtp, string senhaFtp) {
            Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequest inValue = new Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequest();
            inValue.Body = new Copasa.Sigos.Console.SRServidorFTP.EnviaArquivoRequestBody();
            inValue.Body.nomeArquivo = nomeArquivo;
            inValue.Body.identificadorlote = identificadorlote;
            inValue.Body.urlFtp = urlFtp;
            inValue.Body.usuarioFtp = usuarioFtp;
            inValue.Body.senhaFtp = senhaFtp;
            return ((Copasa.Sigos.Console.SRServidorFTP.FilesSoap)(this)).EnviaArquivoAsync(inValue);
        }
    }
}
