//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Copasa.Atende.Util.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Copasa.Util.Digital.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O serviço solicitado já existe, seguem abaixo os dados do registro..
        /// </summary>
        public static string JaExiste {
            get {
                return ResourceManager.GetString("JaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível salvar a coordenada, tente novamente mais tarde..
        /// </summary>
        public static string MSG_COORDENADAS {
            get {
                return ResourceManager.GetString("MSG_COORDENADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Protocolo aberto para {0}.
        /// </summary>
        public static string MSG_EMAIL_SOLICITACAO {
            get {
                return ResourceManager.GetString("MSG_EMAIL_SOLICITACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar os tipos de coplementos. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_ERR_BUSCARCOMPLEMENTO {
            get {
                return ResourceManager.GetString("MSG_ERR_BUSCARCOMPLEMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar as comunicações. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_ERR_BUSCARCOMUNICACAO {
            get {
                return ResourceManager.GetString("MSG_ERR_BUSCARCOMUNICACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível salvar as comunicações. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_ERR_SALVARCOMUNICACAO {
            get {
                return ResourceManager.GetString("MSG_ERR_SALVARCOMUNICACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existe identificador específico para este CPF ou CNPJ. Dúvidas entrar em contato com o fale conosco..
        /// </summary>
        public static string MSG_NAO_TEM_IDENTIFICADOR {
            get {
                return ResourceManager.GetString("MSG_NAO_TEM_IDENTIFICADOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar o histórico de consumo. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC01_ERR_HISTORICO {
            get {
                return ResourceManager.GetString("MSG_UC01_ERR_HISTORICO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existe histórico para o mês de referência..
        /// </summary>
        public static string MSG_UC01_EX01 {
            get {
                return ResourceManager.GetString("MSG_UC01_EX01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível enviar a segunda via de conta via e-mail. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC02_ERR_ENVIAREMAIL {
            get {
                return ResourceManager.GetString("MSG_UC02_ERR_ENVIAREMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar as informações da conta. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC03_ERR_OBTERCONTA {
            get {
                return ResourceManager.GetString("MSG_UC03_ERR_OBTERCONTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar a lista de imóveis. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC04_ERR_LISTAIMOVEIS {
            get {
                return ResourceManager.GetString("MSG_UC04_ERR_LISTAIMOVEIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível obter a certidão negativa de débito. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC04_ERR_OBTERCERTIDAO {
            get {
                return ResourceManager.GetString("MSG_UC04_ERR_OBTERCERTIDAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível incluir os dados do novo usuário. Por favor tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC05_ERR_CADASTRAR {
            get {
                return ResourceManager.GetString("MSG_UC05_ERR_CADASTRAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar os contatos do usuário. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC05_ERR_CONTATOS {
            get {
                return ResourceManager.GetString("MSG_UC05_ERR_CONTATOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar os imóveis. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC05_ERR_IMOVEIS {
            get {
                return ResourceManager.GetString("MSG_UC05_ERR_IMOVEIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar os dados do usuário. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC05_ERR_RECUPERAR {
            get {
                return ResourceManager.GetString("MSG_UC05_ERR_RECUPERAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível salvar o telefone. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC05_ERR_TELEFONE {
            get {
                return ResourceManager.GetString("MSG_UC05_ERR_TELEFONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível autenticar o usuário. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC06_AUTENTICAR {
            get {
                return ResourceManager.GetString("MSG_UC06_AUTENTICAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível enviar o e-mail. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC06_EMAIL {
            get {
                return ResourceManager.GetString("MSG_UC06_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não encontrado..
        /// </summary>
        public static string MSG_UC06_EX01 {
            get {
                return ResourceManager.GetString("MSG_UC06_EX01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha incorreta..
        /// </summary>
        public static string MSG_UC06_EX02 {
            get {
                return ResourceManager.GetString("MSG_UC06_EX02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF ou CNPJ já cadastrado..
        /// </summary>
        public static string MSG_UC06_EX04 {
            get {
                return ResourceManager.GetString("MSG_UC06_EX04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha enviada com sucesso..
        /// </summary>
        public static string MSG_UC06_EX05 {
            get {
                return ResourceManager.GetString("MSG_UC06_EX05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF/CNPJ inválido..
        /// </summary>
        public static string MSG_UC06_EX07 {
            get {
                return ResourceManager.GetString("MSG_UC06_EX07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar a senha. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC06_SENHA {
            get {
                return ResourceManager.GetString("MSG_UC06_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível concluir a solicitação. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC07_ERR_INTERRUPCAO {
            get {
                return ResourceManager.GetString("MSG_UC07_ERR_INTERRUPCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar a lista de localidades. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC07_ERR_LOCALIDADE {
            get {
                return ResourceManager.GetString("MSG_UC07_ERR_LOCALIDADE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar as pavimentações. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC07_ERR_PAV {
            get {
                return ResourceManager.GetString("MSG_UC07_ERR_PAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível gerar a solicitação de vazamento na rua, por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC07_ERR_VAZAMENTO {
            get {
                return ResourceManager.GetString("MSG_UC07_ERR_VAZAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta área não é uma área coberta pela COPASA..
        /// </summary>
        public static string MSG_UC07_EX01 {
            get {
                return ResourceManager.GetString("MSG_UC07_EX01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível gerar a solicitação de vazamento no imóvel, por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC08_ERR_VAZAMENTO {
            get {
                return ResourceManager.GetString("MSG_UC08_ERR_VAZAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Vazamento não encontrado..
        /// </summary>
        public static string MSG_UC08_EX01 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma ordem de serviço aberta para o cliente. A previsão de solução é dia {0}..
        /// </summary>
        public static string MSG_UC08_EX03 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solicitação gerada com sucesso! A previsão de solução é dia {0}. Protocolo: {1}..
        /// </summary>
        public static string MSG_UC08_EX05 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solicitação gerada com sucesso! Protocolo: {0}..
        /// </summary>
        public static string MSG_UC08_EX06 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existe este serviço com esta pavimentação na tabela de serviços..
        /// </summary>
        public static string MSG_UC08_EX07 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para este tipo de serviço, não informe pavimentação.
        /// </summary>
        public static string MSG_UC08_EX08 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua solicitação foi encaminhada para a unidade responsável..
        /// </summary>
        public static string MSG_UC08_EX09 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A sua solicitação de serviço de Vazamento no Imóvel foi gerada com sucesso!.
        /// </summary>
        public static string MSG_UC08_EX11 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os dados desta solicitação foram enviados para o e-mail: {0}..
        /// </summary>
        public static string MSG_UC08_EX12 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A sua solicitação de serviço de Vazamento na Rua foi gerada com sucesso!.
        /// </summary>
        public static string MSG_UC08_EX13 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Endereço inválido..
        /// </summary>
        public static string MSG_UC08_EX14 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma ordem de serviço aberta, estamos reiterando o serviço para execução de urgência, pedimos desculpas pelos transtornos..
        /// </summary>
        public static string MSG_UC08_EX15 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Logradouro {0} não está cadastrado para a Localidade..
        /// </summary>
        public static string MSG_UC08_EX16 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível gerar o vazamento, o endereço não foi localizado em nosso sistema. Gentileza inserir o endereço correto e tentar novamente..
        /// </summary>
        public static string MSG_UC08_EX17 {
            get {
                return ResourceManager.GetString("MSG_UC08_EX17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível obter os dados para leitura. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC10_ERR_OBTERDADOS {
            get {
                return ResourceManager.GetString("MSG_UC10_ERR_OBTERDADOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível salvar os dados de leitura. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC10_ERR_SALVAR {
            get {
                return ResourceManager.GetString("MSG_UC10_ERR_SALVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A leitura para este mês já foi informada..
        /// </summary>
        public static string MSG_UC10_EX01 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A informação de leitura para usuários com mais de 20 pontos, deverá ser realizada somente pelo leiturista.
        /// </summary>
        public static string MSG_UC10_EX010 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Leitura informada é superior à quantidade de números comportados em seu hidrômetro. Preencha corretamente a informação de leitura..
        /// </summary>
        public static string MSG_UC10_EX011 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desistir sem salvar? ___Sim   ___Não .
        /// </summary>
        public static string MSG_UC10_EX02 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, preencha todos os campos obrigatórios..
        /// </summary>
        public static string MSG_UC10_EX03 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário logado não é titular do identificador selecionado..
        /// </summary>
        public static string MSG_UC10_EX04 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua leitura está fora da faixa esperada. Continuar a informação de leitura? SIM  NÃO.
        /// </summary>
        public static string MSG_UC10_EX05 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A informação de leitura é referente à fatura de conta bloqueada do mês {0}. Informe a leitura:.
        /// </summary>
        public static string MSG_UC10_EX06 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A informação de leitura é referente à fatura de conta bloqueada do mês {0}. Será gerada uma nova fatura fora do débito automático..
        /// </summary>
        public static string MSG_UC10_EX06_a {
            get {
                return ResourceManager.GetString("MSG_UC10_EX06_a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data para informação da leitura se encontra fora do prazo. O próximo ciclo inicia-se em : {0}..
        /// </summary>
        public static string MSG_UC10_EX07 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você informou a leitura do seu hidrômetro pelo quarto mês consecutivo. Não será possível a informação de leitura. Gentileza dirigir-se a uma de nossas agências de atendimento mais próxima.
        /// </summary>
        public static string MSG_UC10_EX08 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe leitura para o mês de referência atual..
        /// </summary>
        public static string MSG_UC10_EX09 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O imóvel informado não está hidrometrado. .
        /// </summary>
        public static string MSG_UC10_EX12 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A leitura do hidrômetro foi registrada. Após análise sua conta estará disponível para emissão da segunda via em nosso site e aplicativo..
        /// </summary>
        public static string MSG_UC10_EX13 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua informação de conta bloqueada ainda está sendo processada e você terá que aguardar novo prazo para a informação da sua leitura. A próxima data para a nova informação de leitura será: {0}.
        /// </summary>
        public static string MSG_UC10_EX14 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A operação não pode ser concluída. Por favor, tente novamente..
        /// </summary>
        public static string MSG_UC10_EX15 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível informar a leitura. Matrícula migrada para o COPANOR. Favor ligar para o telefone 08000300005..
        /// </summary>
        public static string MSG_UC10_EX16 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível informar a leitura. Serviço inválido para Cliente Centralizador. Favor comparecer a uma Agência de Atendimento da COPASA..
        /// </summary>
        public static string MSG_UC10_EX17 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível informar a leitura, esta ligação encontra-se cortada. Gentileza solicitar a religação..
        /// </summary>
        public static string MSG_UC10_EX18 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A informação de sua leitura será registrada e caso seja deferida o mês informado sairá do débito automático e posteriormente gerada nova fatura..
        /// </summary>
        public static string MSG_UC10_EX19 {
            get {
                return ResourceManager.GetString("MSG_UC10_EX19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informação de Leitura registrada com sucesso! .
        /// </summary>
        public static string MSG_UC10_RN10 {
            get {
                return ResourceManager.GetString("MSG_UC10_RN10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é possível informar leitura pelo quarto mês consecutivo. .
        /// </summary>
        public static string MSG_UC10_RN11 {
            get {
                return ResourceManager.GetString("MSG_UC10_RN11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A leitura do hidrômetro foi registrada. Após análise sua conta estará disponível para emissão da segunda via em nosso site e aplicativo..
        /// </summary>
        public static string MSG_UC10_RN12 {
            get {
                return ResourceManager.GetString("MSG_UC10_RN12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar os identificadores. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC12_ERR_ATUALIZAR {
            get {
                return ResourceManager.GetString("MSG_UC12_ERR_ATUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível enviar o e-mail com a lista de identificadores. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC12_ERR_EMAIL {
            get {
                return ResourceManager.GetString("MSG_UC12_ERR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível obter a lista dos identificadores. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC12_ERR_OBTER {
            get {
                return ResourceManager.GetString("MSG_UC12_ERR_OBTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível salvar os identificadores. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC12_ERR_SALVAR {
            get {
                return ResourceManager.GetString("MSG_UC12_ERR_SALVAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador inválido..
        /// </summary>
        public static string MSG_UC12_EX01 {
            get {
                return ResourceManager.GetString("MSG_UC12_EX01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O(s) seguinte(s) identificador(es) foi(ram) {0}{1}..
        /// </summary>
        public static string MSG_UC12_EX02 {
            get {
                return ResourceManager.GetString("MSG_UC12_EX02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível gerar a solicitação para estou sem agua. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC13_ERR_SOLICITACAO {
            get {
                return ResourceManager.GetString("MSG_UC13_ERR_SOLICITACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A Copasa está efetuando manutenção na rede de abastecimento na sua região e a previsão de solução é dia {0} às {1}. Foi gerado número de protocolo para o acompanhamento: {2}. Agradecemos pela compreensão..
        /// </summary>
        public static string MSG_UC13_EX01 {
            get {
                return ResourceManager.GetString("MSG_UC13_EX01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Solicitação gerada com sucesso! O número do protocolo para acompanhamento é: {0} para a matrícula {1} no endereço {2}..
        /// </summary>
        public static string MSG_UC13_EX02 {
            get {
                return ResourceManager.GetString("MSG_UC13_EX02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma ordem de serviço aberta para o cliente. A previsão de solução é dia {0} até {1}..
        /// </summary>
        public static string MSG_UC13_EX03 {
            get {
                return ResourceManager.GetString("MSG_UC13_EX03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A sua solicitação de serviço de Estou sem Água gerada com sucesso!.
        /// </summary>
        public static string MSG_UC13_EX04 {
            get {
                return ResourceManager.GetString("MSG_UC13_EX04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os dados desta solicitação foram enviados para o e-mail: {0}..
        /// </summary>
        public static string MSG_UC13_EX05 {
            get {
                return ResourceManager.GetString("MSG_UC13_EX05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma ordem de serviço aberta para o cliente. A previsão de solução é dia {0}..
        /// </summary>
        public static string MSG_UC13_EX06 {
            get {
                return ResourceManager.GetString("MSG_UC13_EX06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma ordem de serviço aberta, estamos reiterando o serviço para execução de urgência, pedimos desculpas pelos transtornos..
        /// </summary>
        public static string MSG_UC13_EX07 {
            get {
                return ResourceManager.GetString("MSG_UC13_EX07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma ordem de serviço aberta para o cliente. A previsão de solução é dia {0} às {1}. Protocolo: {2}..
        /// </summary>
        public static string MSG_UC13_RN09 {
            get {
                return ResourceManager.GetString("MSG_UC13_RN09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar o serviço solicitado. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC14_ERR_ACOMP {
            get {
                return ResourceManager.GetString("MSG_UC14_ERR_ACOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível enviar o e-mail com os detalhes do serviço. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC14_ERR_EMAIL {
            get {
                return ResourceManager.GetString("MSG_UC14_ERR_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possivel obter a ordem de serviço. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC14_ERR_OBTEROS {
            get {
                return ResourceManager.GetString("MSG_UC14_ERR_OBTEROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível recuperar os detalhes do serviço solicitado. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC14_ERR_RECUPERAR {
            get {
                return ResourceManager.GetString("MSG_UC14_ERR_RECUPERAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data limite para atendimento era {0}, estamos reiterando o serviço para execução de urgência, pedimos desculpas pelos transtornos..
        /// </summary>
        public static string MSG_UC14_EX01 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para consultar serviços abertos para o seu CPF ou CNPJ, você deverá estar logado..
        /// </summary>
        public static string MSG_UC14_EX02 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Logradouro inexistente. Gentileza conferir e refazer pesquisa!.
        /// </summary>
        public static string MSG_UC14_EX03 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Número de protocolo inexistente. Por favor confira..
        /// </summary>
        public static string MSG_UC14_EX04 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existe serviço pendente para o usuário logado..
        /// </summary>
        public static string MSG_UC14_EX05 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O serviço solicitado ainda não tem data programada para execução. Acabamos de enviar um email requisitando a previsão para o atendimento e a inserção da data de execução será registrada em até 24h, contudo ratificamos que a data limite de atendimento é para {0}..
        /// </summary>
        public static string MSG_UC14_EX07 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este serviço foi executado no dia {0}..
        /// </summary>
        public static string MSG_UC14_EX08 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este serviço está programado para ser executado até o dia {0}..
        /// </summary>
        public static string MSG_UC14_EX09 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este serviço estava programado para ser executado até o dia {0}, já estamos abrindo uma solicitação de urgência para execução o mais rápido possível. A reprogramação no sistema será registrada em até 24h..
        /// </summary>
        public static string MSG_UC14_EX10 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não existe serviço pendente para esse endereço..
        /// </summary>
        public static string MSG_UC14_EX12 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, preencha o logradouro corretamente..
        /// </summary>
        public static string MSG_UC14_EX15 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por necessidade operacional o serviço foi reprogramado para a data {0} (Data de programação)..
        /// </summary>
        public static string MSG_UC14_EX18 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este serviço está sem data de previsão e já estamos abrindo uma solicitação de urgência para execução o mais rápido possível. A reprogramação no sistema será registrada em até 24h..
        /// </summary>
        public static string MSG_UC14_EX19 {
            get {
                return ResourceManager.GetString("MSG_UC14_EX19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O serviço solicitado de {0} foi executado em {1}. Está pendente ainda o serviço de {2} com previsão de atendimento para {3}..
        /// </summary>
        public static string MSG_UC14_RN29 {
            get {
                return ResourceManager.GetString("MSG_UC14_RN29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O serviço solicitado de {0} foi executado em {1}. Está pendente ainda o serviço de {2} cuja previsão de atendimento era até {3}. Estamos solicitando urgência para execução do serviço para o mais breve possível..
        /// </summary>
        public static string MSG_UC14_RN30 {
            get {
                return ResourceManager.GetString("MSG_UC14_RN30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar o status do e-mail. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC15_EMAIL {
            get {
                return ResourceManager.GetString("MSG_UC15_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar os dados cadastrais. Por favor, tente novamente mais tarde..
        /// </summary>
        public static string MSG_UC15_ERR_ATUALIZACAO {
            get {
                return ResourceManager.GetString("MSG_UC15_ERR_ATUALIZACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha alterada com sucesso..
        /// </summary>
        public static string MSG_UC15_EX10 {
            get {
                return ResourceManager.GetString("MSG_UC15_EX10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A senha atual não corresponde à senha armazenada..
        /// </summary>
        public static string MSG_UC15_EX11 {
            get {
                return ResourceManager.GetString("MSG_UC15_EX11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível alterar a senha. Por favor, tente mais tarde..
        /// </summary>
        public static string MSG_UC15_SENHA {
            get {
                return ResourceManager.GetString("MSG_UC15_SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foi encontrado uma inconsistência na alteração de alguns dados. Entre em contato com a COPASA informando o erro..
        /// </summary>
        public static string MSG_UC16_EX01 {
            get {
                return ResourceManager.GetString("MSG_UC16_EX01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foi verificado que o e-mail do usuário {0} está ativo..
        /// </summary>
        public static string MSG_UC17_RN02 {
            get {
                return ResourceManager.GetString("MSG_UC17_RN02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foi verificado que o e-mail do usuário {0} está inativo..
        /// </summary>
        public static string MSG_UC17_RN03 {
            get {
                return ResourceManager.GetString("MSG_UC17_RN03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Foi verificado que seu e-mail está inconsistente e necessita ser confirmado. Por favor, altere seu e-mail e clique em salvar..
        /// </summary>
        public static string MSG_UC17_RN04 {
            get {
                return ResourceManager.GetString("MSG_UC17_RN04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aguardando retorno do usuário..
        /// </summary>
        public static string MSG_UC17_RN05 {
            get {
                return ResourceManager.GetString("MSG_UC17_RN05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O usuário foi excluído corretamente!.
        /// </summary>
        public static string MSG_USUARIO_EXCLUIDO {
            get {
                return ResourceManager.GetString("MSG_USUARIO_EXCLUIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível localizar o usuário informado..
        /// </summary>
        public static string MSG_USUARIO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("MSG_USUARIO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p style=&apos;font-family:arial&apos;&gt;{0}&lt;/p&gt;.
        /// </summary>
        public static string paragrafo {
            get {
                return ResourceManager.GetString("paragrafo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;p style=&apos;font-family:arial&apos;&gt;&lt;b&gt;{0}&lt;/b&gt;&lt;/p&gt;.
        /// </summary>
        public static string paragrafoNegrito {
            get {
                return ResourceManager.GetString("paragrafoNegrito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O serviço solicitado foi registrado com sucesso, seguem abaixo os dados do registro..
        /// </summary>
        public static string Sucesso {
            get {
                return ResourceManager.GetString("Sucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;table cellpadding=&apos;5&apos; border=&apos;1&apos; border-style=&apos;ridge&apos; cellspacing=&apos;1&apos; style=&apos;font-family:arial;font-size:14;&apos;&gt;.
        /// </summary>
        public static string Tabela {
            get {
                return ResourceManager.GetString("Tabela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;tr&gt;&lt;td&gt;&lt;font color=&apos;#0267b3&apos;&gt;&lt;b&gt;{0}:&lt;/b&gt;&lt;/font&gt;&lt;/td&gt;&lt;td&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;tr&gt;&lt;td&gt;&lt;b&gt;{0}:&lt;/b&gt;&lt;/td&gt;&lt;td&gt;{1}&lt;/td&gt;&lt;/tr&gt;.
        /// </summary>
        public static string trPadrao {
            get {
                return ResourceManager.GetString("trPadrao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a https://www.google.com.br/maps?q={0},{1}&amp;hl=pt-BR.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
    }
}
